name: Build All Platforms

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -r win-x64 --self-contained=true --output ./publish

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-publish
          path: ./publish

  # build-linux:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: '8.0.x'

  #     - name: Restore dependencies
  #       run: dotnet restore

  #     - name: Build
  #       run: dotnet build --configuration Release

  #     - name: Publish
  #       run: dotnet publish -c Release -r linux-x64 --self-contained=true --output ./publish

  #     - name: Upload Linux Artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: linux-publish
  #         path: ./publish

  # build-macos:
  #   runs-on: macos-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: '8.0.x'

  #     - name: Restore dependencies
  #       run: dotnet restore

  #     - name: Build
  #       run: dotnet build --configuration Release

  #     - name: Publish
  #       run: dotnet publish -c Release -r osx-x64 --self-contained=true --output ./publish

  #     - name: Upload macOS Artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: macos-publish
  #         path: ./publish
